services:
    postgres:
        # build: ./database
        image: postgres:16
        container_name: pg-container
        ports:
            - '5432:5432'
        # env_file:
        #     - apps/api/.env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        healthcheck:
            test: ['CMD', 'pg_isready']
            interval: 10s
            timeout: 7s
            retries: 5
            start_period: 10s
        # networks:
        #     - tradel
        volumes:
            - postgresdb:/var/lib/postgresql/data

volumes:
    postgresdb:

# networks:
#     tradel:
#         name: my-tradel-network
