// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

// Client generation does not connect to PostgreSQL, so builds can run without database credentials.
const databaseUrl = process.env.DB_URL ?? process.env.DATABASE_URL ?? '';

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        url: databaseUrl,
    },
});
